"""Built-in presets for the unified SfM + 3DGS pipeline.

This file is auto-generated from the original run_full_pipeline.py.
"""

PRESETS = {
    "fast": {
        "description": "Fast preview (5-10 min total)",
        "expected_time": "5-10 minutes",
        "sfm": {
            "matching_method": "retrieval",
            "global_extractor": "netvlad",
            "extractor": "disk",
            "matcher": "disk-lightglue",
            "num_matched": 15,
            "camera_model": "PINHOLE",
            "sfm_backend": "glomap",
            "data_factor": 4,
        },
        "gsplat": {
            "subcommand": "mcmc",
            "data_factor": 4,
            "max_steps": 10000,
            "eval_steps": [5000, 10000],
            "save_ply": True,
            "batch_size": 1,
            "camera_model": "pinhole",
            "antialiased": True,
            # depth_lambda can be set here or via --gs-override depth_lambda=...
            "depth_lambda": 0.1,
            "strategy": {
                "cap_max": 1000000,
                "min_opacity": 0.005,
                "refine_start_iter": 500,
                "refine_stop_iter": 25000,
                "refine_every": 100,
                "verbose": True,
            },
        },
    },
    "balanced": {
        "description": "Balanced quality/speed (15-25 min total)",
        "expected_time": "15-25 minutes",
        "sfm": {
            "matching_method": "retrieval",
            "global_extractor": "netvlad",
            "extractor": "disk",
            "matcher": "disk-lightglue",
            "num_matched": 20,
            "camera_model": "PINHOLE",
            "sfm_backend": "glomap",
            "data_factor": 8,
        },
        "gsplat": {
            "subcommand": "mcmc",
            "data_factor": 8,
            "max_steps": 30000,
            "eval_steps": [7000, 15000, 30000],
            "save_ply": True,
            "batch_size": 1,
            "camera_model": "pinhole",
            "antialiased": True,
            "depth_lambda": 0.1,
            "strategy": {
                "cap_max": 1000000,
                "min_opacity": 0.005,
                "refine_start_iter": 500,
                "refine_stop_iter": 25000,
                "refine_every": 100,
                "verbose": True,
            },
        },
    },
    "quality": {
        "description": "High quality (40-60 min total)",
        "expected_time": "40-60 minutes",
        "sfm": {
            "matching_method": "retrieval",
            "global_extractor": "netvlad",
            "extractor": "disk",
            "matcher": "disk-lightglue",
            "num_matched": 30,
            "camera_model": "PINHOLE",
            "sfm_backend": "glomap",
            "data_factor": 1,
        },
        "gsplat": {
            "subcommand": "mcmc",
            "data_factor": 1,
            "max_steps": 50000,
            "eval_steps": [10000, 25000, 50000],
            "save_ply": True,
            "batch_size": 1,
            "camera_model": "pinhole",
            "antialiased": True,
            "depth_lambda": 0.1,
            "strategy": {
                "cap_max": 1500000,
                "min_opacity": 0.005,
                "refine_start_iter": 500,
                "refine_stop_iter": 30000,
                "refine_every": 100,
                "verbose": True,
            },
        },
    },
    "ultra": {
        "description": "Maximum quality (1-2 hours total)",
        "expected_time": "1-2 hours",
        "sfm": {
            "matching_method": "exhaustive",
            "global_extractor": "netvlad",
            "extractor": "superpoint_aachen",
            "matcher": "superpoint-lightglue",
            "camera_model": "PINHOLE",
            "sfm_backend": "glomap",
            "data_factor": 1,
        },
        "gsplat": {
            "subcommand": "mcmc",
            "data_factor": 1,
            "max_steps": 100000,
            "eval_steps": [15000, 30000, 60000, 100000],
            "save_ply": True,
            "batch_size": 1,
            "camera_model": "pinhole",
            "antialiased": True,
            "depth_lambda": 0.1,
            "strategy": {
                "cap_max": 2000000,
                "min_opacity": 0.005,
                "refine_start_iter": 500,
                "refine_stop_iter": 50000,
                "refine_every": 100,
                "verbose": True,
            },
        },
    },
}

